/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import controller.DAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Administrador;
import model.Atendente;
import model.Paciente;

/**
 *
 * @author pp
 */
public class Gerenciamento extends javax.swing.JFrame {

    /**
     * Creates new form Gerenciamento
     */
    public Gerenciamento() {
        initComponents();
        //this.setLocationRelativeTo(null);
        centralizarComponente();
        buscarPacienteRemover();
        buscarAtendenteRemover();
        buscarAdmRemover();
        this.setResizable(false);
    }

        public void centralizarComponente() { 
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize(); Dimension dw = getSize(); setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2); 
    }
    
    int i;
    int a;
    int ad;
    
       public void buscarPacienteRemover(){
        
        DAO dao = new DAO();
        try {
            ArrayList<Paciente> paciente = dao.obterPacientesRemover();
            
            Paciente vetorPaciente[] = new Paciente[paciente.size()];
            i = 0;
            paciente.forEach(e -> vetorPaciente[i++] = (Paciente) e);
            
            ComboBoxPaciente.setModel(
                    new DefaultComboBoxModel(vetorPaciente));
            
        }
        
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                    "Lista de Pacientes indisponível! Tente novamente!");
        }

       }
       
       public void buscarAtendenteRemover(){

        DAO dao = new DAO();
        try {
            ArrayList<Atendente> atendente = dao.obterAtendentesRemover();

            Atendente vetorAtendente[] = new Atendente[atendente.size()];
            a = 0;
            atendente.forEach(e -> vetorAtendente[a++] = (Atendente) e);

            ComboBoxAtendente.setModel(
                    new DefaultComboBoxModel(vetorAtendente)); 
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                    "Lista de atendentes indisponível! Tente novamente!");
        }
       }

       public void buscarAdmRemover(){

        DAO dao = new DAO();
        try {
            ArrayList<Administrador> administrador = dao.obterAdmRemover();

            Administrador vetorAdministrador[] = new Administrador[administrador.size()];
            a = 0;
            administrador.forEach(e -> vetorAdministrador[a++] = (Administrador) e);

            ComboBoxAdm.setModel(
                    new DefaultComboBoxModel(vetorAdministrador)); 
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                    "Lista de administradores indisponível! Tente novamente!");
        }
       }
       
       
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ButtonRemovePac = new javax.swing.JButton();
        ComboBoxPaciente = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        ButtonRemoveAten = new javax.swing.JButton();
        ComboBoxAtendente = new javax.swing.JComboBox<>();
        CampoRemoveAdm = new javax.swing.JPanel();
        ButtonRemoveAdm = new javax.swing.JButton();
        ComboBoxAdm = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 153, 102), null, null));
        jPanel4.setMaximumSize(new java.awt.Dimension(548, 662));
        jPanel4.setMinimumSize(new java.awt.Dimension(548, 662));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel2.setText("Remover usuários");
        jLabel2.setToolTipText("");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setForeground(new java.awt.Color(77, 77, 77));
        jLabel5.setText("©️ Copyright - 2021");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\pp\\Desktop\\img covid usjt\\logox_1.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(548, 662));
        jLabel3.setMinimumSize(new java.awt.Dimension(548, 662));

        ButtonVoltar.setBackground(new java.awt.Color(255, 255, 204));
        ButtonVoltar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        ButtonVoltar.setText("Voltar");
        ButtonVoltar.setBorder(new javax.swing.border.MatteBorder(null));
        ButtonVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 14))); // NOI18N

        ButtonRemovePac.setBackground(new java.awt.Color(255, 153, 153));
        ButtonRemovePac.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        ButtonRemovePac.setText("Remover");
        ButtonRemovePac.setBorder(new javax.swing.border.MatteBorder(null));
        ButtonRemovePac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemovePacActionPerformed(evt);
            }
        });

        ComboBoxPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRemovePac, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonRemovePac, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(ComboBoxPaciente))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atendente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 14))); // NOI18N

        ButtonRemoveAten.setBackground(new java.awt.Color(255, 153, 153));
        ButtonRemoveAten.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        ButtonRemoveAten.setText("Remover");
        ButtonRemoveAten.setBorder(new javax.swing.border.MatteBorder(null));
        ButtonRemoveAten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoveAtenActionPerformed(evt);
            }
        });

        ComboBoxAtendente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRemoveAten, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonRemoveAten, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(ComboBoxAtendente))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        CampoRemoveAdm.setBackground(new java.awt.Color(255, 204, 204));
        CampoRemoveAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 14))); // NOI18N

        ButtonRemoveAdm.setBackground(new java.awt.Color(255, 153, 153));
        ButtonRemoveAdm.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        ButtonRemoveAdm.setText("Remover");
        ButtonRemoveAdm.setBorder(new javax.swing.border.MatteBorder(null));
        ButtonRemoveAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoveAdmActionPerformed(evt);
            }
        });

        ComboBoxAdm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout CampoRemoveAdmLayout = new javax.swing.GroupLayout(CampoRemoveAdm);
        CampoRemoveAdm.setLayout(CampoRemoveAdmLayout);
        CampoRemoveAdmLayout.setHorizontalGroup(
            CampoRemoveAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoRemoveAdmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRemoveAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        CampoRemoveAdmLayout.setVerticalGroup(
            CampoRemoveAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoRemoveAdmLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(CampoRemoveAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonRemoveAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(ComboBoxAdm))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButton1.setText("Relatório");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(199, 199, 199))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CampoRemoveAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoRemoveAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Cadastro cad = new Cadastro();
        cad.setVisible(true);
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Relatorio cad = new Relatorio();
        cad.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonRemovePacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemovePacActionPerformed
        DAO dao = new DAO();
         Paciente p = (Paciente) ComboBoxPaciente.getSelectedItem();
        if (p == null)
        {
            JOptionPane.showMessageDialog(this, "Não há pacientes para remover");
        }
         int id =  p.getId();
         int opcao = JOptionPane.showConfirmDialog(this,"Confirma remoção?");


        if (opcao == JOptionPane.YES_OPTION){ 
        try {
            System.out.println("Debugando" + id);
            dao.removerPaciente(id);
            buscarPacienteRemover();
            JOptionPane.showMessageDialog(this, "Paciente removido com sucesso!");
        } catch (Exception ex) {
            Logger.getLogger(Gerenciamento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Falha na remoção!");
        }
        }
        else if (opcao == JOptionPane.NO_OPTION)
        {JOptionPane.showMessageDialog(this, "Paciente não removido!");}
     
    }//GEN-LAST:event_ButtonRemovePacActionPerformed

    private void ButtonRemoveAtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoveAtenActionPerformed
        DAO dao = new DAO();
        Atendente a = (Atendente) ComboBoxAtendente.getSelectedItem();
        if (a == null)
        {
            JOptionPane.showMessageDialog(this, "Não há atendentes para remover");
        }
        int id = a.getId();
        int opcao = JOptionPane.showConfirmDialog(this,"Confirma remoção?");

        if (opcao == JOptionPane.YES_OPTION){
        try
        {
            dao.removerAtendente(id);
            buscarAtendenteRemover();
            JOptionPane.showMessageDialog(this, "Atendente removido com sucesso!");
        }
        catch (Exception ex) {
            Logger.getLogger(Gerenciamento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Falha na remoção!");
        } 
        }
        else if (opcao == JOptionPane.NO_OPTION)
        {JOptionPane.showMessageDialog(this, "Usuário não removido!");}

    }//GEN-LAST:event_ButtonRemoveAtenActionPerformed

    private void ButtonRemoveAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoveAdmActionPerformed
        DAO dao = new DAO();
        Administrador a = (Administrador) ComboBoxAdm.getSelectedItem();
        if (a == null)
        {
            JOptionPane.showMessageDialog(this, "Não há administradores para remover");
        }
        int id = a.getId();
        int opcao = JOptionPane.showConfirmDialog(this,"Confirma remoção?");

        if (opcao == JOptionPane.YES_OPTION){
        try
        {
            dao.removerAdm(id);
            buscarAdmRemover();
            JOptionPane.showMessageDialog(this, "Administrador removido com sucesso!");
        }
        catch (Exception ex) {
            Logger.getLogger(Gerenciamento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Falha na remoção!");
        } 
        }
        else if (opcao == JOptionPane.NO_OPTION)
        {JOptionPane.showMessageDialog(this, "Usuário não removido!");}
    }//GEN-LAST:event_ButtonRemoveAdmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRemoveAdm;
    private javax.swing.JButton ButtonRemoveAten;
    private javax.swing.JButton ButtonRemovePac;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JPanel CampoRemoveAdm;
    private javax.swing.JComboBox<String> ComboBoxAdm;
    private javax.swing.JComboBox<String> ComboBoxAtendente;
    private javax.swing.JComboBox<String> ComboBoxPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
