/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import controller.DAO;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.IntervaloEmDias;

/**
 *
 * @author pp
 */
public class Relatorio extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
        centralizarComponente();
         this.setResizable(false);
    }
    
    public void centralizarComponente() { 
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize(); Dimension dw = getSize(); setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonGerarPdf = new javax.swing.JButton();
        BoxDiaInicio = new javax.swing.JComboBox<>();
        BoxMesInicio = new javax.swing.JComboBox<>();
        BoxAnoInicio = new javax.swing.JComboBox<>();
        BoxDiaFim = new javax.swing.JComboBox<>();
        BoxMesFim = new javax.swing.JComboBox<>();
        BoxAnoFim = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))), "Gerar Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic", 0, 24))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(548, 662));
        jPanel1.setMinimumSize(new java.awt.Dimension(548, 662));
        jPanel1.setPreferredSize(new java.awt.Dimension(548, 500));

        ButtonGerarPdf.setBackground(new java.awt.Color(255, 255, 255));
        ButtonGerarPdf.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        ButtonGerarPdf.setIcon(new javax.swing.ImageIcon("C:\\Users\\pp\\Desktop\\img covid usjt\\impressora_318-1793.jpg")); // NOI18N
        ButtonGerarPdf.setText("Gerar PDF");
        ButtonGerarPdf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 255), null, new java.awt.Color(0, 0, 102)));
        ButtonGerarPdf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonGerarPdf.setPreferredSize(new java.awt.Dimension(80, 23));
        ButtonGerarPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGerarPdfActionPerformed(evt);
            }
        });

        BoxDiaInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BoxMesInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BoxAnoInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));

        BoxDiaFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BoxMesFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BoxAnoFim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025", "2026", "2027" }));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Data inicial:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Data final:");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setForeground(new java.awt.Color(77, 77, 77));
        jLabel5.setText("©️ Copyright - 2021");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        ButtonVoltar.setBackground(new java.awt.Color(153, 153, 255));
        ButtonVoltar.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        ButtonVoltar.setText("Voltar");
        ButtonVoltar.setBorder(new javax.swing.border.MatteBorder(null));
        ButtonVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonVoltarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BoxDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BoxMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BoxAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BoxDiaFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BoxMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BoxAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(78, 78, 78)
                                .addComponent(ButtonGerarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxDiaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxMesInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxAnoInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxDiaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxMesFim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxAnoFim, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(ButtonGerarPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addComponent(ButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonGerarPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGerarPdfActionPerformed

        Document documento = new Document();
        DAO dao = new DAO();
        IntervaloEmDias dias = new IntervaloEmDias();
        int a ,b ,c , d , e, f;
        int[] DiaInicio = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31};
        int[] MesInicio = {1,2,3,4,5,6,7,8,9,10,11,12 };
        int[] AnoInicio = {2021,2022,2023,2024,2025,2026,2027};
        int[] DiaFim = DiaInicio;
        int[] MesFim = MesInicio;
        int[] AnoFim = {2021,2022,2023,2024,2025,2026,2027};
        long retornoDias;
        
       a = BoxDiaInicio.getSelectedIndex();
       b = BoxMesInicio.getSelectedIndex();
       c = BoxAnoInicio.getSelectedIndex();
       d = BoxDiaFim.getSelectedIndex();
       e = BoxMesFim.getSelectedIndex();
       f = BoxAnoFim.getSelectedIndex();
       retornoDias = dias.CalculaDias(DiaInicio[a],
                        MesInicio[b],
                        AnoInicio[c],
                        DiaFim[d],
                        MesFim[e],
                        AnoFim[f]);
       
       String DataInicio = AnoInicio[c] +"-"+ DiaInicio[a] +"-"+ MesInicio[b];
       String DataFim = AnoFim[f] +"-"+ DiaFim[d] +"-"+ MesFim[e];
      
       String dataIniRe = DiaInicio[a]+"/"+MesInicio[b]+"/"+AnoInicio[c];
       String dataFiRe = DiaFim[d]+"/"+MesFim[e]+"/"+AnoFim[f];
       
       
        try
        {
            DecimalFormat df = new DecimalFormat("##0.00");

            PdfWriter.getInstance(documento, new FileOutputStream("Relatório.pdf"));
            documento.open();
            documento.add(new Paragraph("Relatório com a média de pacientes vacinados"));
            documento.add(new Paragraph("Do dia: " + dataIniRe + ", até o dia " + dataFiRe));
            
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("Quantidade de dias: " +" " + retornoDias));
            documento.add(new Paragraph("Quantidade de pessoas vacinadas acima de 90 anos: " + dao.relatorio1(DataInicio,DataFim)));
            documento.add(new Paragraph("Aqui está a média de vacinação diária da idade acima: " + (df.format(dao.relatorio1(DataInicio,DataFim)/retornoDias))));
            
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("Quantidade de dias: " +" " + retornoDias));
            documento.add(new Paragraph("Quantidade de pessoas vacinadas entre 70 a 90 anos: " + dao.relatorio2(DataInicio,DataFim)));
            documento.add(new Paragraph("Aqui está a média de vacinação diária da idade acima: " + (df.format(dao.relatorio2(DataInicio,DataFim)/retornoDias))));
            
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("Quantidade de dias: " +" " + retornoDias));
            documento.add(new Paragraph("Quantidade de pessoas vacinadas entre 50 a 70 anos: " + dao.relatorio3(DataInicio,DataFim)));
            documento.add(new Paragraph("Aqui está a média de vacinação diária da idade acima: " + (df.format(dao.relatorio3(DataInicio,DataFim)/retornoDias))));
            
            documento.add(new Paragraph(" "));
            documento.add(new Paragraph(" "));
            
            documento.add(new Paragraph("Quantidade de dias: " +" " + retornoDias));
            documento.add(new Paragraph("Quantidade de pessoas vacinadas abaixo de 50 anos: " + dao.relatorio4(DataInicio,DataFim)));
            documento.add(new Paragraph("Aqui está a média de vacinação diária da idade acima: " + (df.format(dao.relatorio4(DataInicio,DataFim)/retornoDias))));
            
 
        }catch (FileNotFoundException | DocumentException ex) {

            System.out.println("Erro" +ex);
            //Logger.getLogger(Gerenciamento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Logger.getLogger(Gerenciamento.class.getName()).log(Level.SEVERE, null, ex);
        

        finally
        {
            documento.close();
        }
        
        try {
            Desktop.getDesktop().open(new File("Relatório.pdf"));
        } catch (IOException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ButtonGerarPdfActionPerformed

    private void ButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVoltarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        Gerenciamento cad = new Gerenciamento();       
        cad.setVisible(true);
    }//GEN-LAST:event_ButtonVoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxAnoFim;
    private javax.swing.JComboBox<String> BoxAnoInicio;
    private javax.swing.JComboBox<String> BoxDiaFim;
    private javax.swing.JComboBox<String> BoxDiaInicio;
    private javax.swing.JComboBox<String> BoxMesFim;
    private javax.swing.JComboBox<String> BoxMesInicio;
    private javax.swing.JButton ButtonGerarPdf;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
